# -----------------------------------------------------------------------------
# Sample workflow to show deployment concept
# Author: Urs Roesch https://github.com/uroesch
# Version: 0.1.0
# -----------------------------------------------------------------------------
name: linux-build 

on:
  push:
    branches:
    - main 
jobs:
  linux-build:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Find files of latest commit
      shell: bash
      run: |2+ 
        git show --name-only --pretty=format:"" | while read file; do
          [[ -f ${file} ]] && echo ${file}
        done
